version: 2.1
orbs:
  kubernetes: circleci/kubernetes@0.12.0
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: Update DEPLOY_ENV environment variable using CIRCLE_TAG
          command: |
            echo 'export DEPLOY_ENV=$(echo ${CIRCLE_TAG} | sed 's/-.*//')' >> $BASH_ENV
            source $BASH_ENV
      - run: echo $DEPLOY_ENV
      - run: docker build -t openq/openq-frontend:$CIRCLE_TAG --build-arg deploy_env=$DEPLOY_ENV .
      - run: docker push openq/openq-frontend:$CIRCLE_TAG
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: OpenQ
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^development.*/
                - /^staging.*/
                - /^production.*/
